// MongoDB init script — runs once on first container start
db = db.getSiblingDB("waygo");

// Seed sample places — Barranquilla, Colombia
db.places.insertMany([
  {
    name: "Ventana al Mundo",
    slug: "ventana-al-mundo",
    description: "Mirador icónico en el centro de Barranquilla con vista panorámica al Río Magdalena.",
    country: "Colombia",
    city: "Barranquilla",
    category: "viewpoint",
    validation_radius: 50,
    location: { type: "Point", coordinates: [-74.7908, 10.9851] },
    opening_hours: "Todos los días, 24 horas (espacio público al aire libre)",
    price_range: "Gratis",
    fun_fact: "El monumento representa las cinco culturas que confluyen en el Caribe colombiano y se ha convertido en uno de los símbolos más fotografiados de la ciudad.",
    total_visits: 0,
    total_photos: 0,
    total_likes: 0,
    is_active: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: "Gran Malecón del Río",
    slug: "gran-malecon-del-rio",
    description: "Paseo fluvial de 7km sobre el Río Magdalena. Restaurantes, museos y zonas verdes.",
    country: "Colombia",
    city: "Barranquilla",
    category: "urban",
    validation_radius: 100,
    location: { type: "Point", coordinates: [-74.8008, 10.9639] },
    opening_hours: "Todos los días, 6:00 AM - 10:00 PM",
    price_range: "Gratis (restaurantes y atracciones internas con costo aparte)",
    fun_fact: "Es uno de los malecones fluviales más largos de Latinoamérica, construido sobre terrenos que antes eran bodegas portuarias abandonadas.",
    total_visits: 0,
    total_photos: 0,
    total_likes: 0,
    is_active: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: "Museo del Caribe",
    slug: "museo-del-caribe",
    description: "El museo más importante del Caribe colombiano. Historia, cultura y arte regional.",
    country: "Colombia",
    city: "Barranquilla",
    category: "museum",
    validation_radius: 30,
    location: { type: "Point", coordinates: [-74.7964, 10.9639] },
    opening_hours: "Mar-Vie 8:00 AM-4:30 PM, Sáb-Dom 10:00 AM-4:30 PM (cerrado lunes)",
    price_range: "$18.000 COP adultos, $12.000 COP estudiantes",
    fun_fact: "Alberga la exhibición permanente 'Todo lo que somos', un recorrido inmersivo por la historia, música y tradiciones de la región Caribe.",
    total_visits: 0,
    total_photos: 0,
    total_likes: 0,
    is_active: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: "Castillo de Salgar",
    slug: "castillo-de-salgar",
    description: "Fortaleza colonial del siglo XVI sobre el Mar Caribe. Patrimonio histórico nacional.",
    country: "Colombia",
    city: "Barranquilla",
    category: "monument",
    validation_radius: 30,
    location: { type: "Point", coordinates: [-74.9264, 10.9112] },
    opening_hours: "Mié-Dom 9:00 AM-5:00 PM (cerrado lunes y martes)",
    price_range: "$5.000 COP",
    fun_fact: "Fue construido para defender la costa de los ataques de piratas y corsarios durante la época colonial española.",
    total_visits: 0,
    total_photos: 0,
    total_likes: 0,
    is_active: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
]);

print("Seed data inserted: 4 places in Barranquilla");
