// MongoDB init script — runs once on first container start
db = db.getSiblingDB("waygo");

// Seed sample places — Barranquilla, Colombia
db.places.insertMany([
  {
    name: "Ventana al Mundo",
    slug: "ventana-al-mundo",
    description: "Mirador icónico en el centro de Barranquilla con vista panorámica al Río Magdalena.",
    country: "Colombia",
    city: "Barranquilla",
    category: "viewpoint",
    validation_radius: 50,
    location: { type: "Point", coordinates: [-74.7908, 10.9851] },
    total_visits: 0,
    total_photos: 0,
    total_likes: 0,
    is_active: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: "Gran Malecón del Río",
    slug: "gran-malecon-del-rio",
    description: "Paseo fluvial de 7km sobre el Río Magdalena. Restaurantes, museos y zonas verdes.",
    country: "Colombia",
    city: "Barranquilla",
    category: "urban",
    validation_radius: 100,
    location: { type: "Point", coordinates: [-74.8008, 10.9639] },
    total_visits: 0,
    total_photos: 0,
    total_likes: 0,
    is_active: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: "Museo del Caribe",
    slug: "museo-del-caribe",
    description: "El museo más importante del Caribe colombiano. Historia, cultura y arte regional.",
    country: "Colombia",
    city: "Barranquilla",
    category: "museum",
    validation_radius: 30,
    location: { type: "Point", coordinates: [-74.7964, 10.9639] },
    total_visits: 0,
    total_photos: 0,
    total_likes: 0,
    is_active: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    name: "Castillo de Salgar",
    slug: "castillo-de-salgar",
    description: "Fortaleza colonial del siglo XVI sobre el Mar Caribe. Patrimonio histórico nacional.",
    country: "Colombia",
    city: "Barranquilla",
    category: "monument",
    validation_radius: 30,
    location: { type: "Point", coordinates: [-74.9264, 10.9112] },
    total_visits: 0,
    total_photos: 0,
    total_likes: 0,
    is_active: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
]);

print("Seed data inserted: 4 places in Barranquilla");
